<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <artifactId>org.openhab.binding.voltronic</artifactId>
  <groupId>org.openhab.addons.bundles</groupId>
  <packaging>feature</packaging>

  <version>4.3.0</version>

  <name>openHAB Add-ons :: Bundles :: voltronic Binding</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <ohc.version>4.3.0</ohc.version>
    <sat.version>0.17.0</sat.version>
    <spotless.eclipse.wtp.version>4.21.0</spotless.eclipse.wtp.version>
    <karaf.version>4.4.8</karaf.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>framework</artifactId>
      <version>${karaf.version}</version>
      <type>kar</type>
      <scope>provided</scope>
      <optional>true</optional>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.karaf.features</groupId>
      <artifactId>standard</artifactId>
      <version>${karaf.version}</version>
      <classifier>features</classifier>
      <type>xml</type>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.jdt</groupId>
      <artifactId>org.eclipse.jdt.annotation</artifactId>
      <version>2.4.100</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.openhab.core.bom</groupId>
      <artifactId>org.openhab.core.bom.compile</artifactId>
      <version>${ohc.version}</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.openhab.core.bom</groupId>
      <artifactId>org.openhab.core.bom.openhab-core</artifactId>
      <version>${ohc.version}</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.17</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <version>${karaf.version}</version>
        <extensions>true</extensions>
        <configuration>
          <!-- <startLevel>80</startLevel> -->
          <aggregateFeatures>true</aggregateFeatures>
          <checkDependencyChange>true</checkDependencyChange>
          <failOnDependencyChange>false</failOnDependencyChange>
          <logDependencyChanges>true</logDependencyChanges>
          <overwriteChangedDependencies>true</overwriteChangedDependencies>
        </configuration>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>features-generate-descriptor</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <inputFile>${feature.directory}</inputFile>
            </configuration>
          </execution>
          <execution>
            <id>karaf-feature-verification</id>
            <goals>
              <goal>verify</goal>
            </goals>
            <phase>verify</phase>
            <configuration>
              <descriptors combine.children="append">
                <!-- Apache Karaf -->
                <descriptor>mvn:org.apache.karaf.features/framework/${karaf.version}/xml/features</descriptor>
                <descriptor>mvn:org.apache.karaf.features/standard/${karaf.version}/xml/features</descriptor>
                <!-- Current feature under verification -->
                <descriptor>file:${project.build.directory}/feature/feature.xml</descriptor>
              </descriptors>
              <distribution>org.apache.karaf.features:framework</distribution>
              <javase>${oh.java.version}</javase>
              <framework>
                <feature>framework</feature>
              </framework>
              <features>
                <feature>xxx-openhab-*</feature>
              </features>
              <verifyTransitive>false</verifyTransitive>
              <ignoreMissingConditions>true</ignoreMissingConditions>
              <fail>first</fail>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.openhab.core.tools</groupId>
        <artifactId>i18n-maven-plugin</artifactId>
        <version>4.3.10-SNAPSHOT</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.5.0</version>
      </plugin>
      <plugin>
        <groupId>biz.aQute.bnd</groupId>
        <artifactId>bnd-maven-plugin</artifactId>
        <version>7.1.0</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.openhab.tools.sat</groupId>
        <artifactId>sat-plugin</artifactId>
        <version>${sat.version}</version>
        <configuration>
          <checkstyleProperties>tools/static-code-analysis/checkstyle/ruleset.properties</checkstyleProperties>
          <checkstyleFilter>tools/static-code-analysis/checkstyle/suppressions.xml</checkstyleFilter>
          <spotbugsExclude>tools/static-code-analysis/spotbugs/suppressions.xml</spotbugsExclude>
        </configuration>
        <executions>
          <execution>
            <id>sat-all</id>
            <goals>
              <goal>checkstyle</goal>
              <goal>pmd</goal>
              <goal>spotbugs</goal>
              <goal>report</goal>
            </goals>
            <phase>verify</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.43.0</version>
        <configuration>
          <java>
            <eclipse>
              <file>openhab_codestyle.xml</file>
              <version>${spotless.eclipse.version}</version>
            </eclipse>
            <removeUnusedImports/>
            <importOrder>
              <file>openhab.importorder</file>
            </importOrder>
            <endWithNewline/>
          </java>
          <formats>
            <format>
              <!-- *.xml -->
              <includes>
                <include>src/**/*.xml</include>
              </includes>
              <excludes>
                <exclude>**/pom.xml</exclude>
                <exclude>**/feature.xml</exclude>
                <exclude>src/main/history/**/*.xml</exclude>
                <exclude>src/main/resources/header.xml</exclude>
                <exclude>src/main/resources/footer.xml</exclude>
                <exclude>src/main/resources/input/rss*.xml</exclude>
                <exclude>src/test/resources/**/*.xml</exclude>
              </excludes>
              <eclipseWtp>
                <type>XML</type>
                <files>
                  <file>openhab_wst_xml_files.prefs</file>
                </files>
                <version>${spotless.eclipse.wtp.version}</version>
              </eclipseWtp>
              <trimTrailingWhitespace/>
              <endWithNewline/>
            </format>
            <format>
              <!-- feature.xml -->
              <includes>
                <include>src/main/feature/feature.xml</include>
              </includes>
              <eclipseWtp>
                <type>XML</type>
                <files>
                  <file>openhab_wst_feature_file.prefs</file>
                </files>
                <version>${spotless.eclipse.wtp.version}</version>
              </eclipseWtp>
              <trimTrailingWhitespace/>
              <endWithNewline/>
            </format>
            <format>
              <!-- pom.xml -->
              <includes>
                <include>pom.xml</include>
              </includes>
              <eclipseWtp>
                <type>XML</type>
                <files>
                  <file>openhab_wst_pom_file.prefs</file>
                </files>
                <version>${spotless.eclipse.wtp.version}</version>
              </eclipseWtp>
              <trimTrailingWhitespace/>
              <endWithNewline/>
            </format>
          </formats>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openhab.tools</groupId>
            <artifactId>openhab-codestyle</artifactId>
            <version>${sat.version}</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>codestyle_check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <phase>initialize</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <version>3.1.4</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>3.1.4</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.1</version>
        <configuration>
          <compilerId>eclipse</compilerId>
          <compilerArgs>
            <arg>-annotationpath</arg>
            <arg>CLASSPATH</arg>
            <arg>-classpath</arg>
            <arg>${project.build.directory}/dependency</arg>
            <arg>-err:+nullAnnot(org.eclipse.jdt.annotation.Nullable|org.eclipse.jdt.annotation.NonNull|org.eclipse.jdt.annotation.NonNullByDefault),+inheritNullAnnot,+nullAnnotConflict,-nullUncheckedConversion</arg>
            <arg>-warn:+null,+inheritNullAnnot,-nullUncheckedConversion,+nullAnnotRedundant,+nullDereference</arg>
            <arg>-nowarn:[${project.build.directory}/generated-sources]</arg>
          </compilerArgs>
          <showWarnings>true</showWarnings>
          <showDeprecation>true</showDeprecation>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-eclipse</artifactId>
            <version>2.12.1</version>
          </dependency>
          <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>ecj</artifactId>
            <version>3.36.0</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
    <extensions>
      <extension>
        <groupId>org.openhab.tools.sat</groupId>
        <artifactId>sat-extension</artifactId>
        <version>${sat.version}</version>
      </extension>
    </extensions>
  </build>

  <repositories>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>openhab-release</id>
      <url>https://openhab.jfrog.io/artifactory/libs-release</url>
    </repository>
    <repository>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>openhab-snapshot</id>
      <url>https://openhab.jfrog.io/artifactory/libs-snapshot</url>
    </repository>
  </repositories>
</project>
